//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Dock : Track
{
	public virtual object Symbol
    {
		get;
		set;
	}

    public override char Icon()
    {
        if (Moveable != null)
        {
            return 'D';
        }
        else
        {
            return Moveable[0].Icon();
        }
    }

}

