//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Merge : Switch
{
	public virtual Track tempPrevious
	{
		get;
		set;
	}

	public override void Swap()
	{
		throw new System.NotImplementedException();
	}

}

