//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Moveable
{
    public Track Position;
	public virtual bool isFull
	{
		get;
		set;
	}

    public abstract char Icon();

    public abstract void Move();

    public abstract void Empty();

}

