//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NormalTrack : Track
{
    public override char Icon()
    {
        try
        {
            if (Moveable.Count == 0)
            {
                return '----';
            }
            else
            {
                return Moveable[0].Icon();
            }
        }
        catch
        {
            throw new System.EntryPointNotFoundException();
        }
    }
}

