//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class RangeArea : Track
{
	public virtual object Symbol
	{
		get;
		set;
	}

    public override int CollectPoints()
    {
        throw new NotImplementedException();
    }

    public override char Icon()
    {
        if(Moveable.Count() == 0)
        {
            return '█';
        }
        else
        {
            return 'S';
        }
    }

    public override bool TryMove(Moveable moveable)
    {
        if (NextTrack != null)
        {
            if (NextTrack.Moveable.Count() == 0)
            {
                NextTrack.Moveable.Add(moveable);
                Moveable.Remove(moveable);
                CheckTooMuch();
                return true;
            }
        }
        return false; 
    }
}

