//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Ship : Moveable
{
	public virtual int Cargo
	{
		get;
		set;
	}

	public override void Empty()
	{
		throw new System.NotImplementedException();
	}

	public override void Move()
	{
		throw new System.NotImplementedException();
	}

}

