//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Track
{
	public virtual Char Icon
	{
		get;
		set;
	}

	public virtual Moveable Moveable
	{
		get;
		set;
	}

	public virtual Track nextTrack
	{
		get;
		set;
	}

	public virtual Track previousTrack
	{
		get;
		set;
	}

	public virtual bool nextIsPrevious(Track track)
	{
		throw new System.NotImplementedException();
	}

	public virtual void TryMove(Moveable moveable)
	{
		throw new System.NotImplementedException();
	}

}

