//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameController
{

    Output output = new Output();
    Input input = new Input();
    Boolean inGame = false;

    public GameController()
    {
        StartGame();
    }
    public virtual Game Game
	{
		get;
		set;
	}

	public virtual Output Output
	{
		get;
		set;
	}

	public virtual Input Input
	{
		get;
		set;
	}

	public virtual void StartGame()
	{
        Boolean mainMenu = true;
        output.printMain();
        while (mainMenu)
        {
            ConsoleKeyInfo cki = input.askInputKey("> Press a key to start the game");
            if (cki.KeyChar == cki.KeyChar)
            {
                mainMenu = false;
                generateLevel();
            }
        }

    }

	public virtual void generateLevel()
	{
        output.loadLevel();
        inGame = true;
           
    }
    public void handleInput(ConsoleKey input)
    {
        if (inGame)
        {
            switch (input)
            {
                case ConsoleKey.NumPad1:
                    Console.WriteLine('1');
                    break;
                case ConsoleKey.NumPad2:
                    Console.WriteLine('2');
                    break;
                case ConsoleKey.NumPad3:
                    Console.WriteLine('3');
                    break;
                case ConsoleKey.NumPad4:
                    Console.WriteLine('4');
                    break;
                case ConsoleKey.NumPad5:
                    Console.WriteLine('5');
                    break;
            }
        }
    }

}

