//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameController
{
	public virtual Game Game
	{
		get;
		set;
	}

	public virtual Output Output
	{
		get;
		set;
	}

	public virtual Input Input
	{
		get;
		set;
	}

	public virtual void StartGame()
	{
		throw new System.NotImplementedException();
	}

	public virtual void generateLevel()
	{
		throw new System.NotImplementedException();
	}

}

