//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Output
{
    public void printMain()
    {
        Console.Clear();
        Console.OutputEncoding = Encoding.GetEncoding(866);
        Console.WriteLine("┌────────────────────────────────────────────────────┐");
        Console.WriteLine("| Welkom bij Goudkoorts                              |");
        Console.WriteLine("| Rudolf Wardanjan  |   Pim Westervoort              |");
        Console.WriteLine("|                                                    |");
        Console.WriteLine("└────────────────────────────────────────────────────┘");
    }

    public void printEnd()
    {
        Console.Clear();
        Console.WriteLine("===== GAME OVER =====");

    }

    internal void printLevel()
    {
        Console.Clear();
        Console.WriteLine("┌────────────┐");
        Console.WriteLine("| Goudkoorts |");
        Console.WriteLine("└────────────┘");
        Console.WriteLine("─────────────────────────────────────────────");
        Console.WriteLine("");
        Console.WriteLine("Use Numpad ( 4 | 5 | 6 )");
        Console.WriteLine("Use Numpad (   | 2 | 3 )");
        Console.WriteLine();



    }
}

